<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>QuasarPad</AssemblyName>
    <RootNamespace>QuasarPad</RootNamespace>
    <Version>1.2.0</Version>
    <Authors>QuasarPad Team</Authors>
    <Company>QuasarPad</Company>
    <Product>QuasarPad</Product>
    <Description>Offline Text and Markup Toolkit - Pure Mode Notepad with Markdown to HTML, HTML Test, Text Tools.</Description>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
    <PackageReference Include="Markdig" Version="0.37.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\**\*" />
  </ItemGroup>

</Project>
